.TH SHELL 1 "August 2024" "Shell Manual" "User Commands"

.SH NAME
shell \- a simple shell program

.SH SYNOPSIS
.B shell
[\fBcommand\fR]

.SH DESCRIPTION
.B shell
is a simple shell program that reads commands from the standard input and executes them. It provides a basic command-line interface for interacting with the operating system.

.SH COMMANDS
The shell supports the following commands:

.TP
.B internal commands:
.I print_env
\- prints the environment variables

.TP
.B external commands:
any executable program in the system's \fBPATH\fR

.SH OPTIONS
None

.SH ENVIRONMENT VARIABLES
The shell uses the following environment variables:

.TP
.B PATH
\- the search path for executable programs

.TP
.B environ
\- the environment variables

.SH FUNCTIONS
The shell provides the following functions:

.TP
.B execute(char **args, char *prog_name)
\- executes a command using \fBexecve\fR

.TP
.B read_line(void)
\- reads a line of input from the standard input

.TP
.B fork_execute(char **args, char *prog_name)
\- forks a new process to execute a command

.TP
.B exec_commands(char *command, char *prog_name)
\- tokenizes a command string into individual arguments and executes them

.TP
.B prepare_command(char *args[], char *path)
\- prepares a command by adding the path to the executable if necessary

.TP
.B _strcspn(const char *s1, const char *s2)
\- a custom implementation of the \fBstrcspn\fR function

.SH EXIT STATUS
The shell exits with a status of 0 on success, and a non-zero status on failure.
